name: Publishing
run-name: Publish new collabora release ${{ github.ref_name }}

on:
  [push]
    # tags:
      # - 'co-*'

jobs:
  build:
    runs-on: self-hosted
    container:
      image: klimarev/lo_co_build_env:1.5
      options: --user user
    env:
      lo_repo: CollaboraOnline/online
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout ${{ env.lo_repo }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.lo_repo }}
          ref: cp-23.05.6-2
          path: './online'
          
      - name: Build info 
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server!"
          echo "🔎 This job builds ${{ env.lo_repo }} repository ${{ github.ref_name }} tag for adnroid."
          echo "This job is run from $(whoami)"
          echo "Current directory is $(pwd)"
          echo "Current directory structure: $(ls -la)"
          echo "CollaboraOnline directory size: $(du -sh online)"

      - name: Download LibreOffice core
        run: |
          curl -s -L https://github.com/limarev/build-agent/releases/download/co-23.05.6-2/android_arm64-v8a_core_co-23.05.6-2.tar.gz | tar xvzf -
          ls -la
      # - name: Build ${{ env.target }}
      #   run: |
      #     mkdir -p ${{ env.target }} && cd ${{ env.target }}
      #     ./../entrypoint.sh ${{ matrix.arch }}
      #   env:
      #     LIBREOFFICE_SOURCES_DIR: ./../core

      # - name: Check if ${{ env.target }} contains build files
      #   run: |
      #     du -sh ${{ env.target }}
      #     ls -la ${{ env.target }}

      # - name: Archive ${{ env.target }}/instdir
      #   run: |
      #     tar --totals -czf  ${{ env.target }}.tar.gz ${{ env.target }}/instdir

      # - name: Upload files to a GitHub release
      #   uses: svenstaro/upload-release-action@2.7.0
      #   with:
      #     file: "*.tar.gz"
      #     overwrite: true
      #     file_glob: true
      #     release_name: android_libreoffice_core_${{ github.ref_name }}
      #     body: "These are compiled ${{ env.lo_repo }} ${{ github.ref_name }} for Android for 4 platforms: armeabi-v7a, arm64-v8a, x86, x86_64"
      # - run: echo "🍏 This job's status is ${{ job.status }}."
