name: Test
run-name: Test

on:
  [push]


jobs:
  build:
    runs-on: self-hosted
    container:
      image: klimarev/lo_co_build_env:1.5
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make a 4GB random binary file
        run: |
          dd if=/dev/urandom of=my-4gb-file bs=1M count=4000
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-4gb-file
          compression-level: 0 # no compression
